### ISSUE TITLE
Windows Installation Issue

### ISSUE THREAD

**Issue by seanmuch** [digitalmethodsinitiative/dmi-instascraper#5]
I have had an issue installing DMI-Instagram scraper. I have followed all the required steps but It does not seem as if the installation completes itself - I can not find and open the app anywhere. I have a 64-bit operating system.

1. I try searching for DMI through windows search
2. It asks me to repair
3. After this takes place, I click finish
4. Nothing seems to have changed after, and I need to repeat the process

<img width="589" alt="DMI PHOTO 1" src="https://user-images.githubusercontent.com/66089146/98802772-ad8ef700-240b-11eb-9a52-b87917a89609.png">
<img width="386" alt="DMI PHOTO 2" src="https://user-images.githubusercontent.com/66089146/98802787-b5e73200-240b-11eb-9232-230d81429fe8.png">
<img width="388" alt="DMI PHOTO 3" src="https://user-images.githubusercontent.com/66089146/98802802-bc75a980-240b-11eb-9706-f7cd08cb27b4.png">

**Comment by stijn-uva** [comment]
By default the app installs in `C:\Users\[WINDOWS USERNAME]\AppData\Local\Programs\dmi-instascraper`. Can you find it there?

**Comment by seanmuch** [comment]
> By default the app installs in `C:\Users\[WINDOWS USERNAME]\AppData\Local\Programs\dmi-instascraper`. Can you find it there?

I have just had a look again. It isn't there.

**Comment by stijn-uva** [comment]
Took a while, but there is now a new installer that should work better!
